name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Get Version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Build App Bundle
        run: |
          swift build -c release --product ScanOrganizerApp

      - name: Create App Bundle
        run: |
          APP_NAME="Scan Organizer.app"
          APP_DIR="ScanOrganizer.app"
          CONTENTS_DIR="$APP_DIR/Contents"
          MACOS_DIR="$CONTENTS_DIR/MacOS"
          RESOURCES_DIR="$CONTENTS_DIR/Resources"

          mkdir -p "$MACOS_DIR"
          mkdir -p "$RESOURCES_DIR"

          cp .build/release/ScanOrganizerApp "$MACOS_DIR/ScanOrganizer"

          # Create proper Info.plist with actual values
          cat > "$CONTENTS_DIR/Info.plist" << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>ScanOrganizer</string>
    <key>CFBundleIdentifier</key>
    <string>com.jonaskern.scanorganizer</string>
    <key>CFBundleName</key>
    <string>Scan Organizer</string>
    <key>CFBundleDisplayName</key>
    <string>Scan Organizer</string>
    <key>CFBundleVersion</key>
    <string>${GITHUB_REF#refs/tags/v}</string>
    <key>CFBundleShortVersionString</key>
    <string>${GITHUB_REF#refs/tags/v}</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSMinimumSystemVersion</key>
    <string>14.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
EOF

      - name: Create ZIP Archive
        run: |
          VERSION=${{ steps.version.outputs.version }}
          zip -r "ScanOrganizer-${VERSION}.zip" "ScanOrganizer.app"

      - name: Calculate SHA256
        id: sha
        run: |
          VERSION=${{ steps.version.outputs.version }}
          SHA256=$(shasum -a 256 "ScanOrganizer-${VERSION}.zip" | cut -d' ' -f1)
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT
          echo "SHA256: $SHA256"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ScanOrganizer-${{ steps.version.outputs.version }}.zip
          body: |
            ## Scan Organizer v${{ steps.version.outputs.version }}

            ### Installation

            #### Via Homebrew
            ```bash
            brew install jonaskern-dev/tap/scan-organizer
            ```

            #### Manual Installation
            1. Download ScanOrganizer-${{ steps.version.outputs.version }}.zip
            2. Unzip and move to Applications folder
            3. Install Ollama and required models:
               ```bash
               ollama pull granite3.2-vision:2b
               ollama pull granite3.3:2b
               ```

            ### SHA256
            ```
            ${{ steps.sha.outputs.sha256 }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
